# Generated by Django 5.2.17 on 2026-08-09 16:57

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SendingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Gmail"),
                            ("microsoft", "Outlook / Microsoft 365"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sender_email", models.EmailField(max_length=254)),
                (
                    "access_token",
                    core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "refresh_token",
                    core.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scopes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Space-separated OAuth scopes granted.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("needs_reauth", "Needs re-authorization"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider", "sender_email"),
                        name="unique_account_per_user",
                    )
                ],
            },
        ),
    ]
