"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv.load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-change-me-before-deploying",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h]

# Render sets RENDER_EXTERNAL_HOSTNAME automatically for every service — pick
# it up so ALLOWED_HOSTS/CSRF_TRUSTED_ORIGINS work with zero manual config.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [h for h in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if h]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "django_htmx",
    # Local apps
    "accounts",
    "datafiles",
    "emailtemplates",
    "sending",
    "campaigns",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Local dev defaults to SQLite so `manage.py runserver` works with zero setup.
# In production, set DATABASE_URL (e.g. from Supabase/Neon) and this will be
# used instead — see requirements.txt (dj-database-url) once added, or swap
# this block for `dj_database_url.parse(os.environ["DATABASE_URL"])`.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if os.environ.get("DATABASE_URL"):
    import dj_database_url

    DATABASES["default"] = dj_database_url.parse(os.environ["DATABASE_URL"], conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Uploaded CSV/Excel files. Size-capped in the upload view — see datafiles/views.py.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
MAX_UPLOAD_SIZE_BYTES = int(os.environ.get("MAX_UPLOAD_SIZE_BYTES", 10 * 1024 * 1024))  # 10MB default

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Auth redirects
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "campaigns:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"

# --- App-specific settings (fill in via .env; see .env.example) ---

FIELD_ENCRYPTION_KEY = os.environ.get("FIELD_ENCRYPTION_KEY", "")

GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")

MICROSOFT_OAUTH_CLIENT_ID = os.environ.get("MICROSOFT_OAUTH_CLIENT_ID", "")
MICROSOFT_OAUTH_CLIENT_SECRET = os.environ.get("MICROSOFT_OAUTH_CLIENT_SECRET", "")

# Gmail free-tier daily send cap per connected account (used for UI throttling warnings).
GMAIL_DAILY_SEND_LIMIT = int(os.environ.get("GMAIL_DAILY_SEND_LIMIT", 450))
MS365_DAILY_SEND_LIMIT = int(os.environ.get("MS365_DAILY_SEND_LIMIT", 450))

# Absolute base URL used to build links that go out in emails (unsubscribe
# links), where there's no in-flight request to build them from (e.g. the
# background send worker). Falls back to Render's own hostname, then to
# localhost for dev.
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "")
if not SITE_BASE_URL:
    if RENDER_EXTERNAL_HOSTNAME:
        SITE_BASE_URL = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    else:
        SITE_BASE_URL = "http://localhost:8000"

# Campaigns with more pending recipients than this are queued for the
# background worker (see campaigns/management/commands/send_pending_campaigns.py)
# instead of being sent synchronously inside the request, to avoid request
# timeouts on Render's free plan.
SYNC_SEND_THRESHOLD = int(os.environ.get("SYNC_SEND_THRESHOLD", 25))

# Signup/login abuse safeguards (see core/ratelimit.py). Values are
# "N requests per window_seconds per client IP".
SIGNUP_RATE_LIMIT = (int(os.environ.get("SIGNUP_RATE_LIMIT_COUNT", 8)), int(os.environ.get("SIGNUP_RATE_LIMIT_WINDOW", 3600)))
LOGIN_RATE_LIMIT = (int(os.environ.get("LOGIN_RATE_LIMIT_COUNT", 15)), int(os.environ.get("LOGIN_RATE_LIMIT_WINDOW", 600)))

# A user sending more than this many emails in a rolling 24h window is
# surfaced in /admin/ for manual review (see campaigns/admin.py). Doesn't
# block sending — just flags accounts worth a look, per the platform-abuse
# policy in architecture-plan.md section 6.
SUSPICIOUS_DAILY_SEND_THRESHOLD = int(os.environ.get("SUSPICIOUS_DAILY_SEND_THRESHOLD", 2000))

# --- Production hardening (Render terminates TLS and proxies plain HTTP to us) ---
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 week to start; raise once you're confident everything is served over HTTPS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
