# Generated by Django 5.2.17 on 2026-08-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "subject",
                    models.CharField(
                        help_text="Can include {{variables}}.", max_length=998
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text or simple HTML. Can include {{variables}}."
                    ),
                ),
                ("is_html", models.BooleanField(default=False)),
                (
                    "variables_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Variable names referenced in subject/body.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
